/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import javax.swing.JOptionPane;
import others.LoadOntology;
import others.ReasoningExample;

/**
 *
 * @author Home
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */


    public Home() {
        super("Quadratic Equation Intelligence Tutoring System");
        try {
            LoadOntology.loadOntology("C:\\Users\\HP\\Downloads\\AI-Learning---Java---Protege-19-Dec-main\\AI-Learning---Java---Protege-19-Dec-main\\QuadraticEquationITS\\src\\home\\QuadraticUpdate.owl");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load ontology."
                    + "", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valuea = new javax.swing.JTextField();
        valueB = new javax.swing.JTextField();
        valueC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        discriminantLabel = new javax.swing.JLabel();
        rootTypeLabel = new javax.swing.JLabel();
        solutionLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setPreferredSize(new java.awt.Dimension(785, 675));
        setResizable(false);
        getContentPane().setLayout(null);

        valuea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueaActionPerformed(evt);
            }
        });
        getContentPane().add(valuea);
        valuea.setBounds(90, 100, 90, 30);

        valueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueBActionPerformed(evt);
            }
        });
        getContentPane().add(valueB);
        valueB.setBounds(90, 150, 90, 30);
        getContentPane().add(valueC);
        valueC.setBounds(90, 200, 90, 30);

        jLabel1.setText("Value A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 110, 50, 16);

        jLabel2.setText("Value B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 50, 16);

        jLabel3.setText("Value C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 200, 60, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("to calculate your discriminant");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 300, 260, 25);

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Final Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 430, 140, 23);

        discriminantLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        discriminantLabel.setText("Discriminant: ");
        getContentPane().add(discriminantLabel);
        discriminantLabel.setBounds(20, 350, 180, 24);

        rootTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rootTypeLabel.setText("Root Type: ");
        getContentPane().add(rootTypeLabel);
        rootTypeLabel.setBounds(230, 350, 490, 20);

        solutionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(solutionLabel);
        solutionLabel.setBounds(170, 430, 440, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("To solve a Quadratic Equation. You need to provide your co-efficient Values");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 610, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("Step2 - Calculate Discriminant");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 330, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Click");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 300, 60, 25);

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 300, 90, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 470, 760, 10);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("Step1 - Enter Co-efficient Respectively");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 60, 370, 26);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("Step2 - Calculate Quadratic Equation");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 390, 340, 26);

        jLabel10.setText("Ontology loaded: OntologyID(OntologyIRI(<http://www.semanticweb.org/home/ontologies/2024/11/quadratic_equation>))");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 530, 740, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-12-19 013113.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(490, 10, 280, 150);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    
                 if(!valuea.getText().isEmpty() && !valueB.getText().isEmpty() && !valueC.getText().isEmpty()){
                    double a = Double.parseDouble(valuea.getText());
                    double b = Double.parseDouble(valueB.getText());
                    double c = Double.parseDouble(valueC.getText());

                    // Calculate discriminant
                    double discriminant = b * b - 4 * a * c;

                    // Infer root type
                    String rootType = ReasoningExample.inferAndCheckRoot(String.valueOf(discriminant),a,b,c);

                    // Calculate roots
                    String solutions;
                    
                  if (discriminant > 0) {
                    double root1 = roundToSignificantFigures((-b + Math.sqrt(discriminant)) / (2 * a), 2);
                    double root2 = roundToSignificantFigures((-b - Math.sqrt(discriminant)) / (2 * a), 2);
                    solutions = "Root 1 = " + root1 + ", Root 2 = " + root2;

                } else if (discriminant == 0) {
                    double root = roundToSignificantFigures(-b / (2 * a), 2);
                    solutions = "Repeated Root = " + root;
                } else {
                    double realPart = roundToSignificantFigures(-b / (2 * a), 2);
                    double imaginaryPart = roundToSignificantFigures(Math.sqrt(-discriminant) / (2 * a), 2);
                    solutions = "Root 1 = " + realPart + " + " + imaginaryPart + "i, Root 2 = " + realPart + " - " + imaginaryPart + "i";
                }

                // Display results
                
                solutionLabel.setText("Solutions: " + solutions);

                    }else{
                     JOptionPane.showMessageDialog(Home.this, "Cant Be Empty","Error", JOptionPane.ERROR_MESSAGE);
                 }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valueaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  if(!valuea.getText().isEmpty() && !valueB.getText().isEmpty() && !valueC.getText().isEmpty()){
                    double a = Double.parseDouble(valuea.getText());
                    double b = Double.parseDouble(valueB.getText());
                    double c = Double.parseDouble(valueC.getText());

                    // Calculate discriminant
                    double discriminant = b * b - 4 * a * c;

                    // Infer root type
                    String rootType = ReasoningExample.inferAndCheckRoot(String.valueOf(discriminant),a,b,c);
                    discriminantLabel.setText("Discriminant: " + discriminant);
                rootTypeLabel.setText("Root Type: " + rootType);
  }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public static double roundToSignificantFigures(double num, int sigFig) {
    if (num == 0) return 0;
    final double d = Math.ceil(Math.log10(Math.abs(num))); // Order of magnitude
    final int power = sigFig - (int) d;
    final double magnitude = Math.pow(10, power);
    final long shifted = Math.round(num * magnitude);
    return shifted / magnitude;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel discriminantLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel rootTypeLabel;
    private javax.swing.JLabel solutionLabel;
    private javax.swing.JTextField valueB;
    private javax.swing.JTextField valueC;
    private javax.swing.JTextField valuea;
    // End of variables declaration//GEN-END:variables
}
