/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import javax.swing.JOptionPane;
import others.LoadOntology;
import others.ReasoningExample;

/**
 *
 * @author Home
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */


    public Home() {
        super("Quadratic Equation Intelligence Tutoring System");
        try {
            LoadOntology.loadOntology("C:\\Users\\Home\\Documents\\AI-Learning---Java---Protege-19-Dec\\"
                    + "QuadraticEquationITS\\src\\"
                    + "home\\QuadraticUpdate.owl");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load ontology."
                    + "", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valuea = new javax.swing.JTextField();
        valueB = new javax.swing.JTextField();
        valueC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        discriminantLabel = new javax.swing.JLabel();
        rootTypeLabel = new javax.swing.JLabel();
        solutionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        valuea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueaActionPerformed(evt);
            }
        });
        getContentPane().add(valuea);
        valuea.setBounds(110, 120, 90, 30);

        valueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueBActionPerformed(evt);
            }
        });
        getContentPane().add(valueB);
        valueB.setBounds(110, 170, 90, 30);
        getContentPane().add(valueC);
        valueC.setBounds(110, 210, 90, 30);

        jLabel1.setText("Value A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 120, 50, 16);

        jLabel2.setText("Value B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 170, 50, 16);

        jLabel3.setText("Value C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 210, 60, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Input the respective Co-effcient");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 40, 330, 25);

        jButton1.setText("Calculate and Learn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 270, 139, 25);

        discriminantLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        discriminantLabel.setText("Discriminant: ");
        getContentPane().add(discriminantLabel);
        discriminantLabel.setBounds(220, 160, 257, 24);

        rootTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rootTypeLabel.setText("Root Type: ");
        getContentPane().add(rootTypeLabel);
        rootTypeLabel.setBounds(220, 200, 260, 16);

        solutionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        solutionLabel.setText("SolutionLabel");
        getContentPane().add(solutionLabel);
        solutionLabel.setBounds(220, 230, 330, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    
                 if(!valuea.getText().isEmpty() && !valueB.getText().isEmpty() && !valueC.getText().isEmpty()){
                    double a = Double.parseDouble(valuea.getText());
                    double b = Double.parseDouble(valueB.getText());
                    double c = Double.parseDouble(valueC.getText());

                    // Calculate discriminant
                    double discriminant = b * b - 4 * a * c;

                    // Infer root type
                    String rootType = ReasoningExample.inferRootType(String.valueOf(discriminant));

                    // Calculate roots
                    String solutions;
                    
                  if (discriminant > 0) {
                    double root1 = roundToSignificantFigures((-b + Math.sqrt(discriminant)) / (2 * a), 2);
                    double root2 = roundToSignificantFigures((-b - Math.sqrt(discriminant)) / (2 * a), 2);
                    solutions = "Root 1 = " + root1 + ", Root 2 = " + root2;

                } else if (discriminant == 0) {
                    double root = roundToSignificantFigures(-b / (2 * a), 2);
                    solutions = "Repeated Root = " + root;
                } else {
                    double realPart = roundToSignificantFigures(-b / (2 * a), 2);
                    double imaginaryPart = roundToSignificantFigures(Math.sqrt(-discriminant) / (2 * a), 2);
                    solutions = "Root 1 = " + realPart + " + " + imaginaryPart + "i, Root 2 = " + realPart + " - " + imaginaryPart + "i";
                }

                // Display results
                discriminantLabel.setText("Discriminant: " + discriminant);
                rootTypeLabel.setText("Root Type: " + rootType);
                solutionLabel.setText("Solutions: " + solutions);

                    }else{
                     JOptionPane.showMessageDialog(Home.this, "Cant Be Empty","Error", JOptionPane.ERROR_MESSAGE);
                 }
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valueaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueaActionPerformed

    
    public static double roundToSignificantFigures(double num, int sigFig) {
    if (num == 0) return 0;
    final double d = Math.ceil(Math.log10(Math.abs(num))); // Order of magnitude
    final int power = sigFig - (int) d;
    final double magnitude = Math.pow(10, power);
    final long shifted = Math.round(num * magnitude);
    return shifted / magnitude;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel discriminantLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel rootTypeLabel;
    private javax.swing.JLabel solutionLabel;
    private javax.swing.JTextField valueB;
    private javax.swing.JTextField valueC;
    private javax.swing.JTextField valuea;
    // End of variables declaration//GEN-END:variables
}
